name: Hello World

# cÃ¢nd se ruleazÄƒ
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print Hello
        run: echo "Hello, GitHub Actions ðŸš€"

      - name: Print branch
        run: echo "Branch: ${{ github.ref }}"
